### ISSUE TITLE
Plugin Broken?

### ISSUE THREAD

**Issue by kaizerfreak** [Haplo064/JobIcons#3]
Seems to be nonfunctional after the new patch. No icons showing up at all, just regular name plates.

**Comment by mooondark** [comment]
Next update is in one week, maybe we'll get an update after (or maybe not 😉)

**Comment by mooondark** [comment]
Well, I guess the maintener is not playing anymore. Too sad, it seems to be a nice mod, I wish I could have tested it...

**Comment by Haplo064** [comment]
I am alive, and still coding!
It's completely broken thanks to 5.4, and I'm considering how to rewrite it to work better regardless.
I have one free day next week, before the madness of christmas hits me, so hopefully I can at least get the old (bad) version running then, and work on the better fixed version after that.

Sadly this plugin requires more maintenance than my other ones, which I'm looking at how to reduce.

**Comment by mooondark** [comment]
Good news ! 👍
I didn't want to be harsh, I hope you didn't get it that way.
